tap "homebrew/cask-fonts"
tap "koekeishiya/formulae"
tap "romkatv/powerlevel10k"
tap "jesseduffield/lazygit"
brew "wget"
brew "jq"
brew "openssl"
brew "gpg"
brew "node"
brew "python"
brew "neovim"
brew "tmux"
brew "navi"
brew "lsd"
brew "skhd"
brew "yabai"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "ripgrep"
brew "bottom"
brew "fzf"
brew "gdu"
brew "lazygit"
brew "mas"
cask "postman"
cask "docker"
cask "spotify"
cask "surfshark"
cask "visual-studio-code"
cask "wezterm"
cask "zoom"
cask "slack"
cask "brave-browser"
cask "font-jetbrains-mono-nerd-font"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Telegram", id: 747648890
brew "powerlevel10k"
