#!/bin/sh

echo "Decrypting secrets"
yadm decrypt
echo "Updating the yadm repo origin URL with ssh"
yadm remote set-url origin "git@github.com:FiNEk/dotfiles.git"

system_type=$(uname -s)

# Install oh-my-zsh if it's missing
if [ ! -d "$HOME/.oh-my-zsh" ]; then
	echo "Install oh-my-zsh"
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

if [ "$system_type" = "Darwin" ]; then

	# install homebrew if it's missing
	if ! command -v brew >/dev/null 2>&1; then
		echo "Installing homebrew"
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi

	if [ -f "$HOME/.Brewfile" ]; then
		echo "Updating homebrew bundle"
		brew bundle --global
	fi

fi

# Install AstroNVim if it's missing
if [ ! -d "$HOME/.config/nvim" ]; then
	echo "Installing AstroNVim"
	git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
	git clone git@github.com:FiNEk/astro_nvim.git ~/.config/nvim/lua/user
	nvim --headless -c 'quitall'
fi

echo "Setup complete!"
echo "Things to do:"
echo "Login to Bitwarden"
echo "Enable Brave Sync"
echo "Login to Telegram"
echo "Login to Spotify"
